[workspace]
members = [
  "crates/dfq",
  "crates/dfq-core",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
dfq-core = { path = "crates/dfq-core" }
